url: "https://www.vrbrothersfun.com"
baseurl: "/"
exclude: [node_modules, README.md]

reCaptcha:
    siteKey: "6LcmFuIUAAAAANXea98ULYohsOFw2kfQBslDmvMM"
    secret: "6LcmFuIUAAAAAC1shkNJdV6PGME3-rLRItApelQS"
